---
abstract: 'Dochazka REST server'
author:
  - 'Nathan Cutler <ncutler@suse.cz>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.141170'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Dochazka-REST
provides:
  App::Dochazka::REST:
    file: lib/App/Dochazka/REST.pm
    version: '0.066'
  App::Dochazka::REST::Model::Activity:
    file: lib/App/Dochazka/REST/Model/Activity.pm
    version: '0.066'
  App::Dochazka::REST::Model::Employee:
    file: lib/App/Dochazka/REST/Model/Employee.pm
    version: '0.066'
  App::Dochazka::REST::Model::Interval:
    file: lib/App/Dochazka/REST/Model/Interval.pm
    version: '0.066'
  App::Dochazka::REST::Model::Lock:
    file: lib/App/Dochazka/REST/Model/Lock.pm
    version: '0.066'
  App::Dochazka::REST::Model::Privhistory:
    file: lib/App/Dochazka/REST/Model/Privhistory.pm
    version: '0.066'
  App::Dochazka::REST::Model::Schedhistory:
    file: lib/App/Dochazka/REST/Model/Schedhistory.pm
    version: '0.066'
  App::Dochazka::REST::Model::Schedintvls:
    file: lib/App/Dochazka/REST/Model/Schedintvls.pm
    version: '0.066'
  App::Dochazka::REST::Model::Schedule:
    file: lib/App/Dochazka/REST/Model/Schedule.pm
    version: '0.066'
  App::Dochazka::REST::Model::Shared:
    file: lib/App/Dochazka/REST/Model/Shared.pm
    version: '0.066'
  App::Dochazka::REST::Spec:
    file: lib/App/Dochazka/REST/Spec.pm
    version: '0.066'
  App::Dochazka::REST::Util::Factory:
    file: lib/App/Dochazka/REST/Util/Factory.pm
    version: '0.066'
  App::Dochazka::REST::Util::Timestamp:
    file: lib/App/Dochazka/REST/Util/Timestamp.pm
    version: '0.066'
requires:
  App::CELL: '0.183'
  File::ShareDir: '1.00'
resources:
  license: http://opensource.org/licenses/BSD-3-Clause
version: '0.066'
